# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d60a9c385ee1917c5205771940cd0d18ba526b1acbcafc5209930e4b4118345127b30b610656b4a948bdd5b02504315834c4e05d89e961ce21eb91b47d47bc6c

test:
  secret_key_base: 7aa547f7f3775420471ad0d42a310a33c899643878766634031ff232a0a55e82f2b1dab39674706b50fee0f51cf98a7db17764194d3e399056b5c063922cb9df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
